[package]
name = "swfextract"
version = "0.1.0"
edition = "2021"

[dependencies]
bitstream-io = { version = "1.6" }
clap = { version = "4.2", features = ["derive"] }
swf = { version = "0.2" }
sxd-document = { version = "0.3" }
